name: Build and dockerize project

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - name: Build executable
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v ./...
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/superwave1999/tuble-server-2:latest
          docker push ghcr.io/superwave1999/tuble-server-2:latest
